In [ ]:
Домашнее задание "Продвинутая линейная алгебра".
Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:
a) Диагональная, ортогональная, но не единичная(!)
b) Верхнетреугольная, ортогональная
c) Нижнетреугольная, ортогональная
d) Матрица, у которой определитель = 1, и все элементы не равны 0
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
              [1, 3]])
print(m)

Уровень 1:
Найдите спектральное разложение матрицы:
m = np.array([[1, 2],
              [2,3]])
print(m)

Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного количества компонент PCA.
В качестве метрики различия предлагаю использовать MSE.*

У PCA есть метод transform и inverse_transofrm. Первый - снижает размерность, второй - восстанавливает оригинальные данные с потерей информации. Надо посчитать насколько в среднем точно восстанавливается оригинальная картинка в зависимости от количества компонент в PCA.
В качестве справки можно использовать:
https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html - Документация по PCA
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html - Документация по MSE
Картинки цифр можно взять отсюда - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

a) Диагональная, ортогональная, но не единичная(!)

In [55]:
A = np.array([[-1, 0], [0, -1]])

A

array([[-1,  0],
       [ 0, -1]])

In [58]:
AT = A.transpose()
A.dot(AT)

array([[1, 0],
       [0, 1]])

b) Верхнетреугольная, ортогональная

Треугольная (нижнетреугольная - матрица у которой все элементы над главной диагональю равны 0,
верхнетреугольная - матрица у которой все элементы под главной диагональю равны 0)




In [59]:
F = np.eye(3)

F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
FT = F.transpose()
F.dot(FT)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

c) Нижнетреугольная, ортогональная

In [61]:
G = np.eye(3)

G

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
GT = G.transpose()
G.dot(GT)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [50]:
A = np.array([[4, 1], [3, 1]])

A

array([[4, 1],
       [3, 1]])

In [51]:
np.linalg.det(A)

1.0

Найдите собственные значения и собственные вектора матриц:

In [17]:
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [19]:
w, v = np.linalg.eig(m)

In [20]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


Уровень 1:

Найдите спектральное разложение матрицы:

In [31]:
from scipy import linalg

m = np.array([[1, 2],
              [2,3]])

m

array([[1, 2],
       [2, 3]])

In [32]:
a, U = linalg.eig(m)
print('Eigenvalues:')
print(np.array(a, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


<ipython-input-32-37fa174d601d>:3: ComplexWarning: Casting complex values to real discards the imaginary part
  print(np.array(a, dtype=float))


In [33]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]


<ipython-input-33-5b74137712d0>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))
