In [3]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [7]:
import numpy as np

In [18]:
N=10
print(np.arange(N-1,-1,-1))

[9 8 7 6 5 4 3 2 1 0]


In [2]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [29]:
N=10
matrix = np.diag(np.arange(N,-1,-1), k=0)
matrix_sum = sum(np.diagonal(matrix))
print(matrix)
print(matrix_sum)

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
55


In [30]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [7]:
a = np.array([[4,2,1], [1,3,0], [0,5,4]])
b = np.array([4,12,-3])
from numpy import linalg
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [45]:
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

# На сайт заходит очередной посетитель, о покупках которого известно следующее:
    
    next_user_stats = np.array([0, 1, 2, 0, 0, 0])
    
#     Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем
#     и всеми пользователями из массива user_stats

IndentationError: unexpected indent (<ipython-input-45-616a568a0e7a>, line 21)

In [9]:
 users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
    
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [55]:
def cosine (a, b):   
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b) 
    return np.dot(a, b) / (aLength * bLength)
    cos_list = []
    
for user in users_stats:
    cos_list.append(cosine(next_user_stats, user))
max_cos = users_stats[cos_list.index(max(cos_list))]
print(f'поведение нового посетителя схоже с {max_cos}')




поведение нового посетителя схоже с [0 1 1 0 0 0]
